# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BastionCli < Formula
  desc "Bastion CLI"
  homepage "https://github.com/dcdavidev/bastion"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dcdavidev/bastion/releases/download/v0.4.0/bastion_darwin_amd64.tar.gz"
      sha256 "2bfc674a51282c05675553462685f214f867fe5943674169522ba3578e50c622"

      define_method(:install) do
        bin.install "bastion-cli" => "bastion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dcdavidev/bastion/releases/download/v0.4.0/bastion_darwin_arm64.tar.gz"
      sha256 "92fa4eb247734bcf2aa3bbc51cc8b41b7cbde4eb55069a6f2f88aacf28805ecf"

      define_method(:install) do
        bin.install "bastion-cli" => "bastion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcdavidev/bastion/releases/download/v0.4.0/bastion_linux_amd64.tar.gz"
      sha256 "5991a74477a30e2f3aeaa531a39f4cdbf8c0a773c4a43aeae59fc809e375029c"
      define_method(:install) do
        bin.install "bastion-cli" => "bastion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dcdavidev/bastion/releases/download/v0.4.0/bastion_linux_arm64.tar.gz"
      sha256 "5ba09ceb923d73a724212134336307c6f649bccb34ba8eb8f8eaaf0d03f81e17"
      define_method(:install) do
        bin.install "bastion-cli" => "bastion"
      end
    end
  end
end
