# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dropdx < Formula
  desc "dropdx CLI"
  homepage "https://github.com/dropdx/dropdx"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropdx/dropdx/releases/download/v0.6.2/dropdx_darwin_amd64.tar.gz"
      sha256 "ff51b9256f078946d03ad57a7a405c0177dbf4b4d97d8c2e56d93be6580f3c44"

      define_method(:install) do
        bin.install "dropdx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropdx/dropdx/releases/download/v0.6.2/dropdx_darwin_arm64.tar.gz"
      sha256 "bd3bff67fd7b0a8cdcbf19f088071683024b58814a4314481b82aa9c355e241f"

      define_method(:install) do
        bin.install "dropdx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dropdx/dropdx/releases/download/v0.6.2/dropdx_linux_amd64.tar.gz"
      sha256 "0152e791b11049ca44cb8bd5219a98d7447cbfe3fcacdff14a728be5dfcdfaff"
      define_method(:install) do
        bin.install "dropdx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dropdx/dropdx/releases/download/v0.6.2/dropdx_linux_arm64.tar.gz"
      sha256 "2414155d60019437b3e885d083e7bdd6f8b019eb4ce6b846d57a5bafea6e921c"
      define_method(:install) do
        bin.install "dropdx"
      end
    end
  end
end
