# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dropdx < Formula
  desc "dropdx CLI"
  homepage "https://github.com/dropdx/dropdx"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dropdx/dropdx/releases/download/v0.2.0/dropdx_darwin_amd64.tar.gz"
      sha256 "fbfc3bd50bc77859d4258763f017e62c761caa46c7828a0b2e187cfd18b5d8fd"

      define_method(:install) do
        bin.install "dropdx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dropdx/dropdx/releases/download/v0.2.0/dropdx_darwin_arm64.tar.gz"
      sha256 "1e0281c22f6474ec40f56e6cdaf52dcabca652c141fb5ba5730443150305457a"

      define_method(:install) do
        bin.install "dropdx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dropdx/dropdx/releases/download/v0.2.0/dropdx_linux_amd64.tar.gz"
      sha256 "2e6e0ce8941ac07c41af82b2717f8b93ee52dca5511b650b80ad8f1a31f646eb"
      define_method(:install) do
        bin.install "dropdx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dropdx/dropdx/releases/download/v0.2.0/dropdx_linux_arm64.tar.gz"
      sha256 "536854f0dacc110312a2625ccdd1147094fac44c726878d9858b2bb959ca4e04"
      define_method(:install) do
        bin.install "dropdx"
      end
    end
  end
end
